version: '3'

services:
  concourse-db:
    image: postgres:9.6
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: concourse
      POSTGRES_PASSWORD: password
      PGDATA: /database

  concourse-web:
    image: concourse/concourse
    links:
    - concourse-db
    command: web
    ports:
    - "8080:8080"
    volumes: ["./keys/web:/concourse-keys"]
    restart: unless-stopped
    environment:
      CONCOURSE_BASIC_AUTH_USERNAME: concourse
      CONCOURSE_BASIC_AUTH_PASSWORD: concourse
      CONCOURSE_EXTERNAL_URL: "${CONCOURSE_EXTERNAL_URL}"
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: concourse
      CONCOURSE_POSTGRES_PASSWORD: password
      CONCOURSE_POSTGRES_DATABASE: concourse

  concourse-worker:
    image: concourse/concourse
    privileged: true
    links:
    - concourse-web
    command: worker
    volumes: ["./keys/worker:/concourse-keys"]
    environment:
      CONCOURSE_TSA_HOST: concourse-web

  minio:
    image: minio/minio
    volumes:
    - outputs:/export
    ports: ["9000:9000"]
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: miniostorage
    command: server /export

  httpd:
    image: httpd:latest
    ports: ["8090:80"]
    volumes:
    - outputs:/usr/local/apache2/htdocs

volumes:
  outputs:
