resource_types:

resources:

- name: frontend
  type: git
  source:
    uri: https://github.com/igrs/concourse-example-frontend.git
    branch: master

- name: api
  type: git
  source:
    uri: https://github.com/igrs/concourse-example-api.git
    branch: master

- name: bucket
  type: s3
  source:
    endpoint: http://minio:9000
    bucket: outputs
    disable_ssl: true
    skip_ssl_verification: true
    access_key_id: minio
    secret_access_key: miniostorage
    regexp: "reports/(.*)-report.html"
jobs:
- name: frontend-test
  plan:
  - get: frontend
    trigger: true
  - task: fr-unit
    file: frontend/ci/tasks/unit.yml
  - put: bucket
    params:
      file: reports/*-report.html
      acl: public-read

- name: api-test
  plan:
  - get: api
    trigger: true
  - task: api-unit
    file: api/ci/tasks/unit.yml
  - put: bucket
    params:
      file: reports/*-report.html
      acl: public-read

# Dummy integration
- name: integration-test
  plan:
  - aggregate:
    - get: frontend
      trigger: true
      passed:
      - frontend-test
    - get: api
      trigger: true
      passed:
      - api-test
  - task: integration-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alpine
      outputs:
      - name: reports
      run:
        path: sh
        args:
        - -exc
        - |
          echo "Integration test success" > reports/integration-report.html
          find /tmp -name integration-report.html
  - put: bucket
    params:
      file: reports/*-report.html
      acl: public-read

# Dummy Deploy
- name: deploy
  plan:
  - aggregate:
    - get: frontend
      trigger: true
      passed:
      - integration-test
    - get: api
      trigger: true
      passed:
      - integration-test
  - task: deploy
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alpine
      outputs:
      - name: reports
      run:
        path: sh
        args:
        - -exc
        - |
          echo "Deploy test success" > reports/deploy-report.html
          find /tmp -name deploy-report.html
  - put: bucket
    params:
      file: reports/*-report.html
      acl: public-read
