resource_types:

resources:

- name: frontend
  type: git
  source:
    uri: https://github.com/igrs/concourse-example-frontend.git
    branch: master

- name: api
  type: git
  source:
    uri: https://github.com/igrs/concourse-example-api.git
    branch: master

#- name: bucket
#  type: s3
#  source:
#    endpoint: http://minio:9000
#    bucket: outputs
#    disable_ssl: true
#    skip_ssl_verification: true
#    access_key_id: minio
#    secret_access_key: miniostorage

jobs:
- name: frontend-test
  plan:
  - get: frontend
    trigger: true
  - task: fr-unit
    file: frontend/ci/tasks/unit.yml
  #- put: bucket
  #  params:
  #    #file: report/test-report.html
  #    acl: public-read

- name: api-test
  plan:
  - get: api
    trigger: true
  - task: api-unit
    file: api/ci/tasks/unit.yml

- name: integreation-test
  plan:
  - aggregate:
    - get: frontend
      trigger: true
      passed: [frontend-test]
    - get: api
      trigger: true
      passed: [api-test]
  - task: say-hello
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: alpine}
      run:
        path: echo
        args: [Integration test success (dummy)!!"]

